package com.ziggfreed.kweebec.arena;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;

import javax.annotation.Nonnull;

/**
 * The fixed coordinate layout of the Chase grove. Gameplay (shrine relight, gate
 * alert, escape) is driven entirely off these anchors, so the round is fully
 * playable even before any decorative prefab is pasted - the visual geometry is
 * a polish layer over this skeleton, never a dependency of the logic.
 *
 * <p>All anchors are arena-local world coordinates. The instance spawn provider
 * in {@code Server/Instances/KweebecNightmare_Chase/instance.bson} must agree
 * with {@link #SPAWN}. The floor is generated by the {@code KweebecNightmare_Grove}
 * worldgen, whose {@code Base} height is 80: a perfectly FLAT play disc out to
 * radius ~70 (the gameplay footprint), then rolling hills, then a finite cliff
 * edge into the void. Every anchor here sits inside that flat disc, so the
 * walkable surface top is world Y=80 ({@link #STAND_Y}) over a top solid block at
 * Y=79 ({@link #FLOOR_Y}). Spawning below that (the original Y=65) buried players
 * inside solid terrain. The lone exception is {@link #SHRINE_CAVE}, a deliberately
 * sub-surface anchor inside a carved chamber (the descend-underground objective).
 */
public final class ArenaLayout {

    /** Top solid floor-block Y for the {@code KweebecNightmare_Grove} worldgen flat disc (surface top is one above, at Y=80). */
    public static final double FLOOR_Y = 79.0;

    /** Standing/walkable surface Y (one above the floor block). Matches instance.bson spawn + the worldgen Base=80. */
    public static final double STAND_Y = FLOOR_Y + 1.0;

    /** Where players (and the lobby return fallback) spawn in. Matches instance.bson. */
    public static final Anchor SPAWN = new Anchor(0.5, STAND_Y, 0.5, 0f);

    /** The Heartwood Gate that opens when the final shrine is lit. */
    public static final Anchor GATE = new Anchor(0.5, STAND_Y, -44.0, (float) Math.PI);

    /** The exit just past the gate - reaching it (in ESCAPE) wins the round. */
    public static final Anchor ESCAPE = new Anchor(0.5, STAND_Y, -56.0, (float) Math.PI);

    /** The hunter's containment / entry point during PREP, away from the party. */
    public static final Anchor HUNTER_DEN = new Anchor(0.5, STAND_Y, 40.0, (float) Math.PI);

    /**
     * The underground relight shrine: the survivor must DESCEND a carved shaft to reach it.
     * Inside the flat play disc (r~19, so the surface above it stays flat and the shaft top is
     * standable) but well off the surface shrine ring and the gate corridor. Its Y is the cave
     * chamber's stand level (one above the chamber floor at world Y=65), distinct from the ring
     * shrines' {@link #STAND_Y}, so the Y-band proximity guard in {@code ChaseMode} lets it be
     * channelled ONLY from inside the chamber, never from the surface directly above. The shaft (a
     * facing-independent 3x3 spiral staircase the survivor walks back up), the chamber, and the
     * shrine pillar are the {@code KweebecNightmare/Relight_Shaft} prefab, carved into the solid disc
     * by a {@code force} paste (see {@code ArenaBuilder}).
     */
    public static final double CAVE_STAND_Y = 66.0;

    /**
     * Deterministic anchors for the underground relight shrines (one per
     * {@code RuleSet.caveShrineCount()}). All sit inside the flat play disc (r~19-21) so the surface
     * above each stays flat and standable, in distinct quadrants well clear of the surface shrine ring
     * (r26), the gate corridor, the hunter den, and each other (chambers never overlap). Each carves a
     * descent shaft + chamber; {@code ArenaBuilder} alternates the descent style (spiral / ladder) by
     * index for variety.
     */
    private static final Anchor[] CAVE_ANCHORS = {
            new Anchor(13.5, CAVE_STAND_Y, 13.5, (float) Math.PI),
            new Anchor(-18.5, CAVE_STAND_Y, 6.5, (float) Math.PI),
            new Anchor(18.5, CAVE_STAND_Y, -10.5, (float) Math.PI),
            new Anchor(-12.5, CAVE_STAND_Y, -16.5, (float) Math.PI),
    };

    /** The first (canonical) underground shrine anchor; the single-cave default. */
    public static final Anchor SHRINE_CAVE = CAVE_ANCHORS[0];

    /**
     * The first {@code count} underground shrine anchors (clamped to the predefined set). An empty
     * list when {@code count <= 0} (a pure-surface round).
     */
    @Nonnull
    public static List<Anchor> caveShrineAnchors(int count) {
        int n = Math.max(0, Math.min(count, CAVE_ANCHORS.length));
        List<Anchor> out = new ArrayList<>(n);
        for (int i = 0; i < n; i++) {
            out.add(CAVE_ANCHORS[i]);
        }
        return out;
    }

    /**
     * The seeded variant of {@link #caveShrineAnchors(int)}: picks {@code count} cave anchors as a
     * seed-SHUFFLED SUBSET of the predefined set (rather than always the first {@code count}), so the
     * underground objectives sit in a different quadrant combination per round while still being the
     * same distinct, non-overlapping chambers. The anchors themselves (and {@link #CAVE_STAND_Y}) are
     * unchanged, so {@code ArenaBuilder.pasteCaveShaft}'s SurfaceProbe snap still lands each chamber.
     *
     * @param count number of cave shrines ({@code RuleSet.caveShrineCount()}; clamped to the set)
     * @param seed  the per-round world seed ({@code RoundInstance.worldSeed()})
     */
    @Nonnull
    public static List<Anchor> caveShrineAnchors(int count, long seed) {
        int n = Math.max(0, Math.min(count, CAVE_ANCHORS.length));
        if (n == 0) {
            return new ArrayList<>(0);
        }
        // Shuffle the full predefined set off the seed, then take the first n. A dedicated salt keeps
        // this stream independent of the ring-rotation derivation, so the two do not move in lockstep.
        List<Anchor> pool = new ArrayList<>(CAVE_ANCHORS.length);
        for (Anchor a : CAVE_ANCHORS) {
            pool.add(a);
        }
        Collections.shuffle(pool, new Random(seed ^ 0x5DEECE66DL));
        return new ArrayList<>(pool.subList(0, n));
    }

    /** Radius of the shrine ring around spawn. */
    private static final double SHRINE_RING_RADIUS = 26.0;

    /** Proximity radius (blocks) a player must be within to channel a shrine or reach the exit. */
    public static final double INTERACT_RADIUS = 3.0;
    public static final double INTERACT_RADIUS_SQ = INTERACT_RADIUS * INTERACT_RADIUS;

    /**
     * Reaching within this of {@link #ESCAPE} counts as an escape. Generous (the exit pad
     * is 3 blocks across) so a player who clearly reached the exit always resolves the win.
     */
    public static final double ESCAPE_RADIUS = 6.0;
    public static final double ESCAPE_RADIUS_SQ = ESCAPE_RADIUS * ESCAPE_RADIUS;

    private ArenaLayout() {
    }

    /**
     * Evenly-spaced shrine anchors on a ring, deterministic for a given count so
     * every client agrees on the same layout. The ring biases the first shrine
     * toward the gate side so the party drifts toward the exit as they relight.
     *
     * @param count number of shrines ({@code RuleSet.shrineCount(partySize)})
     */
    @Nonnull
    public static List<Anchor> shrineAnchors(int count) {
        return shrineAnchors(count, 0.0);
    }

    /**
     * The seeded variant of {@link #shrineAnchors(int)}: the SAME evenly-spaced ring, but ROTATED by a
     * seed-derived angular offset so the shrine positions (and the gate-side bias) differ per round
     * while staying a uniform ring every client agrees on. The ring radius, {@link #STAND_Y}, and the
     * even spacing are unchanged, so the surface-shrine SurfaceProbe snap in {@code ArenaBuilder} still
     * lands each pillar.
     *
     * @param count number of shrines ({@code RuleSet.shrineCount(partySize)})
     * @param seed  the per-round world seed ({@code RoundInstance.worldSeed()})
     */
    @Nonnull
    public static List<Anchor> shrineAnchors(int count, long seed) {
        // A seed-derived rotation in [0, 2pi). Deterministic for a given seed so every client agrees;
        // distinct for distinct rounds so the ring orientation varies. A salt independent of the cave
        // shuffle keeps the two seed-derivations from moving in lockstep.
        Random rng = new Random(seed * 0x9E3779B97F4A7C15L);
        double offset = rng.nextDouble() * 2.0 * Math.PI;
        return shrineAnchors(count, offset);
    }

    /**
     * Build the shrine ring with an explicit angular {@code rotationOffset} (radians) applied to every
     * shrine. The no-seed {@link #shrineAnchors(int)} passes {@code 0.0} (the original layout); the
     * seeded {@link #shrineAnchors(int, long)} passes a seed-derived offset.
     */
    @Nonnull
    private static List<Anchor> shrineAnchors(int count, double rotationOffset) {
        List<Anchor> out = new ArrayList<>(Math.max(0, count));
        if (count <= 0) {
            return out;
        }
        for (int i = 0; i < count; i++) {
            double theta = (2.0 * Math.PI * i) / count + rotationOffset;
            double x = SPAWN.x() + SHRINE_RING_RADIUS * Math.sin(theta);
            double z = SPAWN.z() - SHRINE_RING_RADIUS * Math.cos(theta);
            // Face the shrine roughly back toward spawn.
            float yaw = (float) Math.atan2(SPAWN.x() - x, SPAWN.z() - z);
            out.add(new Anchor(x, STAND_Y, z, yaw));
        }
        return out;
    }
}
