package com.ziggfreed.kweebec.arena;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Nonnull;

/**
 * The fixed coordinate layout of the Chase grove. Gameplay (shrine relight, gate
 * alert, escape) is driven entirely off these anchors, so the round is fully
 * playable even before any decorative prefab is pasted - the visual geometry is
 * a polish layer over this skeleton, never a dependency of the logic.
 *
 * <p>All anchors are arena-local world coordinates. The instance spawn provider
 * in {@code Server/Instances/KweebecNightmare_Chase/instance.bson} must agree
 * with {@link #SPAWN}. The floor is generated by the {@code KweebecNightmare_Grove}
 * worldgen, whose {@code Base} height is 80: a perfectly FLAT play disc out to
 * radius ~70 (the gameplay footprint), then rolling hills, then a finite cliff
 * edge into the void. Every anchor here sits inside that flat disc, so the
 * walkable surface top is world Y=80 ({@link #STAND_Y}) over a top solid block at
 * Y=79 ({@link #FLOOR_Y}). Spawning below that (the original Y=65) buried players
 * inside solid terrain. The lone exception is {@link #SHRINE_CAVE}, a deliberately
 * sub-surface anchor inside a carved chamber (the descend-underground objective).
 */
public final class ArenaLayout {

    /** Top solid floor-block Y for the {@code KweebecNightmare_Grove} worldgen flat disc (surface top is one above, at Y=80). */
    public static final double FLOOR_Y = 79.0;

    /** Standing/walkable surface Y (one above the floor block). Matches instance.bson spawn + the worldgen Base=80. */
    public static final double STAND_Y = FLOOR_Y + 1.0;

    /** Where players (and the lobby return fallback) spawn in. Matches instance.bson. */
    public static final Anchor SPAWN = new Anchor(0.5, STAND_Y, 0.5, 0f);

    /** The Heartwood Gate that opens when the final shrine is lit. */
    public static final Anchor GATE = new Anchor(0.5, STAND_Y, -44.0, (float) Math.PI);

    /** The exit just past the gate - reaching it (in ESCAPE) wins the round. */
    public static final Anchor ESCAPE = new Anchor(0.5, STAND_Y, -56.0, (float) Math.PI);

    /** The hunter's containment / entry point during PREP, away from the party. */
    public static final Anchor HUNTER_DEN = new Anchor(0.5, STAND_Y, 40.0, (float) Math.PI);

    /**
     * The underground relight shrine: the survivor must DESCEND a carved shaft to reach it.
     * Inside the flat play disc (r~19, so the surface above it stays flat and the shaft top is
     * standable) but well off the surface shrine ring and the gate corridor. Its Y is the cave
     * chamber's stand level (one above the chamber floor at world Y=65), distinct from the ring
     * shrines' {@link #STAND_Y}, so the Y-band proximity guard in {@code ChaseMode} lets it be
     * channelled ONLY from inside the chamber, never from the surface directly above. The shaft (a
     * facing-independent 3x3 spiral staircase the survivor walks back up), the chamber, and the
     * shrine pillar are the {@code KweebecNightmare/Relight_Shaft} prefab, carved into the solid disc
     * by a {@code force} paste (see {@code ArenaBuilder}).
     */
    public static final double CAVE_STAND_Y = 66.0;

    /**
     * Deterministic anchors for the underground relight shrines (one per
     * {@code RuleSet.caveShrineCount()}). All sit inside the flat play disc (r~19-21) so the surface
     * above each stays flat and standable, in distinct quadrants well clear of the surface shrine ring
     * (r26), the gate corridor, the hunter den, and each other (chambers never overlap). Each carves a
     * descent shaft + chamber; {@code ArenaBuilder} alternates the descent style (spiral / ladder) by
     * index for variety.
     */
    private static final Anchor[] CAVE_ANCHORS = {
            new Anchor(13.5, CAVE_STAND_Y, 13.5, (float) Math.PI),
            new Anchor(-18.5, CAVE_STAND_Y, 6.5, (float) Math.PI),
            new Anchor(18.5, CAVE_STAND_Y, -10.5, (float) Math.PI),
            new Anchor(-12.5, CAVE_STAND_Y, -16.5, (float) Math.PI),
    };

    /** The first (canonical) underground shrine anchor; the single-cave default. */
    public static final Anchor SHRINE_CAVE = CAVE_ANCHORS[0];

    /**
     * The first {@code count} underground shrine anchors (clamped to the predefined set). An empty
     * list when {@code count <= 0} (a pure-surface round).
     */
    @Nonnull
    public static List<Anchor> caveShrineAnchors(int count) {
        int n = Math.max(0, Math.min(count, CAVE_ANCHORS.length));
        List<Anchor> out = new ArrayList<>(n);
        for (int i = 0; i < n; i++) {
            out.add(CAVE_ANCHORS[i]);
        }
        return out;
    }

    /** Radius of the shrine ring around spawn. */
    private static final double SHRINE_RING_RADIUS = 26.0;

    /** Proximity radius (blocks) a player must be within to channel a shrine or reach the exit. */
    public static final double INTERACT_RADIUS = 3.0;
    public static final double INTERACT_RADIUS_SQ = INTERACT_RADIUS * INTERACT_RADIUS;

    /**
     * Reaching within this of {@link #ESCAPE} counts as an escape. Generous (the exit pad
     * is 3 blocks across) so a player who clearly reached the exit always resolves the win.
     */
    public static final double ESCAPE_RADIUS = 6.0;
    public static final double ESCAPE_RADIUS_SQ = ESCAPE_RADIUS * ESCAPE_RADIUS;

    private ArenaLayout() {
    }

    /**
     * Evenly-spaced shrine anchors on a ring, deterministic for a given count so
     * every client agrees on the same layout. The ring biases the first shrine
     * toward the gate side so the party drifts toward the exit as they relight.
     *
     * @param count number of shrines ({@code RuleSet.shrineCount(partySize)})
     */
    @Nonnull
    public static List<Anchor> shrineAnchors(int count) {
        List<Anchor> out = new ArrayList<>(Math.max(0, count));
        if (count <= 0) {
            return out;
        }
        for (int i = 0; i < count; i++) {
            double theta = (2.0 * Math.PI * i) / count;
            double x = SPAWN.x() + SHRINE_RING_RADIUS * Math.sin(theta);
            double z = SPAWN.z() - SHRINE_RING_RADIUS * Math.cos(theta);
            // Face the shrine roughly back toward spawn.
            float yaw = (float) Math.atan2(SPAWN.x() - x, SPAWN.z() - z);
            out.add(new Anchor(x, STAND_Y, z, yaw));
        }
        return out;
    }
}
